################################################################
# Traefik logs configuration
################################################################
log:
  # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  level: INFO
################################################################
# Access logs configuration
################################################################
accessLog:
  filePath: /log/access.log
  bufferingSize: 100
  filters:    
    statusCodes:
      - 200
      - 300-302
      - 400-499
    retryAttempts: true
    minDuration: 10ms
################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8080"
################################################################
# Providers
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false 
    network: proxy
  file:
    directory: /configurations/
    watch: true
    debugLogGeneratedTemplate: true