################################################################
# Traefik logs configuration
################################################################
log:
  # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  level: DEBUG

global:
  checkNewVersion: true
  sendAnonymousUsage: true
################################################################
# Access logs configuration
################################################################
accessLog:
  filePath: /log/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - 200
      - 300-302
      - 400-499
    retryAttempts: true
    minDuration: 10ms
################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
################################################################
# Providers
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    network: proxy
    defaultRule: "Host(`{{ .Name }}.{{ index .Labels \"com.docker.compose.service\"}}.dev.local`)"
  file:
    directory: /configurations/
    watch: true
    debugLogGeneratedTemplate: true
################################################################
# SSL Resolvers
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: admin
      storage: /etc/acme/acme.json
      tlsChallenge: true
      caserver: https://ca.dev.local:9000/acme/acme/directory
      # httpChallenge:
      #   entryPoint: web
