version: '3.3'
########################### NETWORKS
# Create proxy network
# $ docker network create proxy
networks:
  proxy:
    external: true
########################### SERVICES
services:
####Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy
  traefik:
    image: traefik:$TRAEFIKVERSION
    container_name: traefik
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Add folder with STATIC configuration yml
      - ./traefik_config/traefik.yml:/traefik.yml:ro
      - ./traefik_config/log/access.log:/log/access.log
      # Add folder with DYNAMIC configuration yml
      - ./traefik_config/configurations:/configurations
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.traefik-http-rtr.rule=Host(`$DOMAINNAME`) && (PathPrefix(`/traefik`))
      - traefik.http.routers.traefik-http-rtr.entrypoints=http
      ## Service Rules
      - traefik.http.routers.traefik-http-rtr.service=api@internal
      - traefik.http.routers.traefik-http-rtr.middlewares=chain-traefik@file
####Portainer is a lightweight management UI which allows you to easily manage your different Docker
  portainer:
    container_name: portainer
    image: portainer/portainer:$PORTAINERVERSION
    restart: always
    depends_on:
      - traefik
    command: -H unix:///var/run/docker.sock
    expose:
      - 9000
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.portainer-http-rtr.entrypoints=http
      - traefik.http.routers.portainer-http-rtr.rule=Host(`$DOMAINNAME`) && (PathPrefix(`/portainer`))
      - traefik.http.routers.portainer-http-rtr.middlewares=chain-regex-prefix@file
####whoami test in front page
  whoami:
    container_name: frontpage
    image: containous/whoami
    restart: always
    depends_on:
      - traefik
    expose:
      - 80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.whoami-http-rtr.rule=Host(`$DOMAINNAME`)
      - traefik.http.routers.whoami-http-rtr.entrypoints=http
      - traefik.http.routers.whoami-http-rtr.middlewares=whoamisub
      ## Middlewares Rules
      - traefik.http.middlewares.whoamisub.stripprefix.prefixes=/example
      - traefik.http.middlewares.whoamisub.stripprefix.forceslash=false
####MariaDB
  mariadb:
    image: mariadb:$MARIAVERSION
    container_name: mariadb
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - proxy
    volumes:
      - /home/jokerlight/Downloads/Docker/mariadb/config:/config
      - /home/jokerlight/Downloads/Docker/mariadb/mysql:/var/lib/mysql
    # ports:
    # - "3306:3306/tcp"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    labels:
      - traefik.enable=false
####phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:$PHPMYADMINVERSION
    restart: always
    depends_on:
      - traefik
    expose:
      - 80
    networks:
      - proxy
    environment:
      PMA_HOSTS: mariadb
    labels:
      - traefik.enable=true
      ## Routers Rules
      - traefik.http.routers.phpmyadmin-http-rtr.rule=Host(`$DOMAINNAME`) && (PathPrefix(`/phpmyadmin`))
      - traefik.http.routers.phpmyadmin-http-rtr.entrypoints=http
      - traefik.http.routers.phpmyadmin-http-rtr.middlewares=chain-regex-prefix@file