# Dynamic configuration
http:
  routers:
    api-router:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      # tls:
      #   certResolver: letsencrypt
      entryPoints:
        - http

